package li.jesse.leetcode;

/*
389. Find the Difference
Easy

Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Example:
Input:
s = "abcd"
t = "abcde"
Output:
e

Explanation:
'e' is the letter that was added.

 */

public class FindTheDifference
{
    public static char findTheDifference(String s, String t)
    {
        for (int i = 0; i < t.length(); i++)
        {
            if (s.charAt(i) != t.charAt(i))
            {
                return t.charAt(i);
            }
        }

        return ' ';
    }

    public static char findTheDifference2(String s, String t)
    {
        char temp = 0;
        for(int i = 0; i < s.length(); i++)
        {
            temp = (char) (temp ^ s.charAt(i));
            System.out.print(temp);
        }

        for(int j = 0; j < t.length(); j++)
        {
            temp = (char) (temp ^ t.charAt(j));
            System.out.print(temp);
        }

        return 'w';
    }
}
